version: '2'

services:

  nginx:
    container_name: sf.nginx
    build: .docker/nginx
    volumes_from:
      - app
    ports:
      - "81:80"

  app:
    container_name: sf.app
    build: .docker/php
    volumes:
      - .:/app
      - ./var/logs:/app/var/logs
      - ./var/cache.:/app/var/cache
    depends_on:
          - mysql

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1﻿